export const reminderDelete = () => {
	try {
		return "reminder";
	} catch (e) {
		console.error("Error:", e);
	}
};
